### ISSUE TITLE
kaip paleisti testus?

### ISSUE THREAD

**Issue by MarijusIL** [front-end-by-rimantas/27g-questions-and-answers#2]
Codewars'ų klausimas:

jeigu startinis kodas yra toks :

```
 const Calculator = function () {
  this.evaluate = (string) => {}
}; 
```

o testus leis šitaip: 

``` 
describe('Example', () => {
	it('Tests', () => {
		var calculate = new Calculator()`
		Test.assertApproxEquals(calculate.evaluate('127'), 127);
		Test.assertApproxEquals(calculate.evaluate('2 + 3'), 5);
		Test.assertApproxEquals(calculate.evaluate('2 - 3 - 4'), -5);
		Test.assertApproxEquals(calculate.evaluate('10 * 5 / 2'), 25);
	});
});
 ```

Klausimas: kaip man pasileisti pačiam testus, naudojant console.Log()? ką turėčiau paduoti console.log, kad galėčiau išbandyti kaip veikia mano parašytas kodas?

**Comment by belauzas** [comment]
Išsikopijuoti testus ir atitinkąmą dalį pasikeisti į `console.log`
```js
console.log(calculate.evaluate('127'), 127);
console.log(calculate.evaluate('2 + 3'), 5);
console.log(calculate.evaluate('2 - 3 - 4'), -5);
console.log(calculate.evaluate('10 * 5 / 2'), 25);
```

**Comment by MarijusIL** [comment]
![image](https://user-images.githubusercontent.com/78425010/118770047-836e3400-b889-11eb-98fe-5e416facca4b.png)
gaunu tuomet tokį:/ 

čiuju atsikandau daugiau, negu galiu sukramtyti. 3kyu užduotis :D
